name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      PLATFORMS: linux/amd64,linux/arm64,linux/arm64/v8

    strategy:
      fail-fast: false
      matrix:
        package:
        - dbt-bigquery
        - dbt-clickhouse
        base:
        - python:3.11.6-slim-bookworm
        - python:3.12.0-slim-bookworm
        include:
        - package: dbt-bigquery
          package_version: 1.7.2
          core_version: 1.7.2
          flavor-package: bigquery
        - package: dbt-clickhouse
          package_version: 1.7.1
          core_version: 1.7.4
          flavor-package: clickhouse
        - base: python:3.11.6-slim-bookworm
          flavor-os: py3.11-bookworm
        - base: python:3.12.0-slim-bookworm
          flavor-os: py3.12-bookworm
        - base: python:3.12.0-slim-bookworm
          flavor-os-latest: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      id: config
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "image-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "image-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    - name: Setup - QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'linux/amd64' }}

    - name: Setup - Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor: |-
          latest=${{ !!matrix.latest }}
        tags: |-
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.package_version }},suffix=-${{ matrix.flavor-package }},enable=${{ !!matrix.flavor-package && !!matrix.flavor-os-latest }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.package_version }},suffix=-${{ matrix.flavor-package }},enable=${{ !!matrix.flavor-package && !!matrix.flavor-os-latest }}
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.package_version }},suffix=-${{ matrix.flavor-package }}-${{ matrix.flavor-os }},enable=${{ !!matrix.flavor-package && !!matrix.flavor-os }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.package_version }},suffix=-${{ matrix.flavor-package }}-${{ matrix.flavor-os }},enable=${{ !!matrix.flavor-package && !!matrix.flavor-os }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        build-args: |
          base=${{ matrix.base }}
          core_version=${{ matrix.core_version }}
          package=${{ matrix.package }}
          package_version=${{ matrix.package_version }}
        push: true
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'linux/amd64' }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
